export const mockIssuesForTests = [    {
    "url": "https://api.github.com/repos/facebook/react/issues/28946",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28946/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28946/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28946/events",
    "html_url": "https://github.com/facebook/react/issues/28946",
    "id": 2268244498,
    "node_id": "I_kwDOAJy2Ks6HMqoS",
    "number": 28946,
    "title": "[React 19] React warns about \"fetchpriority\" props",
    "user": {
        "login": "ascorbic",
        "id": 213306,
        "node_id": "MDQ6VXNlcjIxMzMwNg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/213306?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ascorbic",
        "html_url": "https://github.com/ascorbic",
        "followers_url": "https://api.github.com/users/ascorbic/followers",
        "following_url": "https://api.github.com/users/ascorbic/following{/other_user}",
        "gists_url": "https://api.github.com/users/ascorbic/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ascorbic/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ascorbic/subscriptions",
        "organizations_url": "https://api.github.com/users/ascorbic/orgs",
        "repos_url": "https://api.github.com/users/ascorbic/repos",
        "events_url": "https://api.github.com/users/ascorbic/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ascorbic/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-29T06:40:14Z",
    "updated_at": "2024-04-29T06:40:14Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "## Summary\r\n\r\nIn 18.2.0, React allowed the `fetchpriority` prop in all lower case, but did not accept camelized `fetchPriority`. Support for the camelized version was added in #25927, but it seems to have broken the lowercased version. This means there is no variant that works in both 18.2 and 18.3 canary/19 beta.\r\n\r\nRepro: https://codesandbox.io/p/sandbox/nameless-bird-wvv84h",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28946/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28946/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28945",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28945/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28945/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28945/events",
    "html_url": "https://github.com/facebook/react/pull/28945",
    "id": 2268102591,
    "node_id": "PR_kwDOAJy2Ks5t9ph0",
    "number": 28945,
    "title": "pranav added a message",
    "user": {
        "login": "PranavBobade",
        "id": 66084057,
        "node_id": "MDQ6VXNlcjY2MDg0MDU3",
        "avatar_url": "https://avatars.githubusercontent.com/u/66084057?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/PranavBobade",
        "html_url": "https://github.com/PranavBobade",
        "followers_url": "https://api.github.com/users/PranavBobade/followers",
        "following_url": "https://api.github.com/users/PranavBobade/following{/other_user}",
        "gists_url": "https://api.github.com/users/PranavBobade/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/PranavBobade/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/PranavBobade/subscriptions",
        "organizations_url": "https://api.github.com/users/PranavBobade/orgs",
        "repos_url": "https://api.github.com/users/PranavBobade/repos",
        "events_url": "https://api.github.com/users/PranavBobade/events{/privacy}",
        "received_events_url": "https://api.github.com/users/PranavBobade/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-04-29T04:35:14Z",
    "updated_at": "2024-04-29T06:01:42Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28945",
        "html_url": "https://github.com/facebook/react/pull/28945",
        "diff_url": "https://github.com/facebook/react/pull/28945.diff",
        "patch_url": "https://github.com/facebook/react/pull/28945.patch",
        "merged_at": null
    },
    "body": "<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `main`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test --prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn test --debug --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\n\r\n<!--\r\n Explain the **motivation** for making this change. What existing problem does the pull request solve?\r\n-->\r\n\r\n## How did you test this change?\r\n\r\n<!--\r\n  Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface.\r\n  How exactly did you verify that your PR solves the issue you wanted to solve?\r\n  If you leave this empty, your PR will very likely be closed.\r\n-->\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28945/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28945/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28944",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28944/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28944/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28944/events",
    "html_url": "https://github.com/facebook/react/pull/28944",
    "id": 2268050587,
    "node_id": "PR_kwDOAJy2Ks5t9eJL",
    "number": 28944,
    "title": "chore: export cjs/umd as v17",
    "user": {
        "login": "vctqs1",
        "id": 30227910,
        "node_id": "MDQ6VXNlcjMwMjI3OTEw",
        "avatar_url": "https://avatars.githubusercontent.com/u/30227910?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vctqs1",
        "html_url": "https://github.com/vctqs1",
        "followers_url": "https://api.github.com/users/vctqs1/followers",
        "following_url": "https://api.github.com/users/vctqs1/following{/other_user}",
        "gists_url": "https://api.github.com/users/vctqs1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/vctqs1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vctqs1/subscriptions",
        "organizations_url": "https://api.github.com/users/vctqs1/orgs",
        "repos_url": "https://api.github.com/users/vctqs1/repos",
        "events_url": "https://api.github.com/users/vctqs1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/vctqs1/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-29T03:31:29Z",
    "updated_at": "2024-04-29T03:36:15Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28944",
        "html_url": "https://github.com/facebook/react/pull/28944",
        "diff_url": "https://github.com/facebook/react/pull/28944.diff",
        "patch_url": "https://github.com/facebook/react/pull/28944.patch",
        "merged_at": null
    },
    "body": "<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `main`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test --prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn test --debug --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\nResolve: https://github.com/facebook/react/issues/28371\r\n\r\n<!--\r\n Explain the **motivation** for making this change. What existing problem does the pull request solve?\r\n-->\r\n\r\n## How did you test this change?\r\n\r\n<!--\r\n  Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface.\r\n  How exactly did you verify that your PR solves the issue you wanted to solve?\r\n  If you leave this empty, your PR will very likely be closed.\r\n-->\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28944/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28944/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28943",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28943/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28943/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28943/events",
    "html_url": "https://github.com/facebook/react/issues/28943",
    "id": 2267622177,
    "node_id": "I_kwDOAJy2Ks6HKSsh",
    "number": 28943,
    "title": "Bug: Spurious warnings in react dev runtime about using \"key\" property in spread object",
    "user": {
        "login": "EricMCornelius",
        "id": 748917,
        "node_id": "MDQ6VXNlcjc0ODkxNw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/748917?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/EricMCornelius",
        "html_url": "https://github.com/EricMCornelius",
        "followers_url": "https://api.github.com/users/EricMCornelius/followers",
        "following_url": "https://api.github.com/users/EricMCornelius/following{/other_user}",
        "gists_url": "https://api.github.com/users/EricMCornelius/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/EricMCornelius/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/EricMCornelius/subscriptions",
        "organizations_url": "https://api.github.com/users/EricMCornelius/orgs",
        "repos_url": "https://api.github.com/users/EricMCornelius/repos",
        "events_url": "https://api.github.com/users/EricMCornelius/events{/privacy}",
        "received_events_url": "https://api.github.com/users/EricMCornelius/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 155984160,
            "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
            "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
            "name": "Status: Unconfirmed",
            "color": "d4c5f9",
            "default": false,
            "description": "A potential issue that we haven't yet confirmed as a bug"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-28T15:01:02Z",
    "updated_at": "2024-04-29T05:41:07Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "This warning: https://github.com/facebook/react/blame/190cc990e01e5131a6b26f1a3212444cebd794e2/packages/react/src/jsx/ReactJSXElement.js#L530\r\n\r\nIs triggering any time a rest-spread operator passes a key in an array.\r\n\r\nThat means even intentional and valid situations like:\r\n\r\n```javascript\r\nimport {createRoot} from 'react-dom/client';\r\n\r\nconst component_props = [{\r\n  key: 'my id',\r\n  style: {\r\n    color: 'red'\r\n  },\r\n  children: 'test'\r\n}, {\r\n  key: 'my second id',\r\n  style: {\r\n    color: 'green'\r\n  },\r\n  children: 'test2'\r\n}];\r\n\r\nconst ComponentArray = props => component_props.map(p => <div {...p}/>);\r\n\r\nconst root = document.getElementById('root');\r\nconst vdom = createRoot(root);\r\n\r\nvdom.render(<ComponentArray/>);\r\n```\r\n\r\nAre generating a heap of warnings when running in dev mode.\r\n\r\nI understand the intention to try to avoid unintentional overwriting of a separate supplied key, but is the intention honestly to say you can no longer supply keys externally whatsoever?\r\n\r\nReact version: 18.2.0\r\n\r\n## Steps To Reproduce\r\n\r\nRun the sample above.\r\n\r\n## The current behavior\r\n\r\nGenerates the following warning in development mode:\r\n\r\n```\r\nreact_jsx-dev-runtime.js:92 Warning: A props object containing a \"key\" prop is being spread into JSX:\r\n  let props = {key: someKey, style: ..., children: ...};\r\n  <div {...props} />\r\nReact keys must be passed directly to JSX without using spread:\r\n  let props = {style: ..., children: ...};\r\n  <div key={someKey} {...props} />\r\n    at ComponentArray\r\n```\r\n\r\n## The expected behavior\r\n\r\nNo warning should be generated - there is no other JSX key property being passed that might cause a collision here.",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28943/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28943/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28942",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28942/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28942/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28942/events",
    "html_url": "https://github.com/facebook/react/pull/28942",
    "id": 2267330774,
    "node_id": "PR_kwDOAJy2Ks5t7GNm",
    "number": 28942,
    "title": "[Fix] Simplify pendingState type in useActionState",
    "user": {
        "login": "yongsk0066",
        "id": 46309806,
        "node_id": "MDQ6VXNlcjQ2MzA5ODA2",
        "avatar_url": "https://avatars.githubusercontent.com/u/46309806?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/yongsk0066",
        "html_url": "https://github.com/yongsk0066",
        "followers_url": "https://api.github.com/users/yongsk0066/followers",
        "following_url": "https://api.github.com/users/yongsk0066/following{/other_user}",
        "gists_url": "https://api.github.com/users/yongsk0066/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/yongsk0066/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yongsk0066/subscriptions",
        "organizations_url": "https://api.github.com/users/yongsk0066/orgs",
        "repos_url": "https://api.github.com/users/yongsk0066/repos",
        "events_url": "https://api.github.com/users/yongsk0066/events{/privacy}",
        "received_events_url": "https://api.github.com/users/yongsk0066/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2024-04-28T04:18:33Z",
    "updated_at": "2024-04-28T21:40:43Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28942",
        "html_url": "https://github.com/facebook/react/pull/28942",
        "diff_url": "https://github.com/facebook/react/pull/28942.diff",
        "patch_url": "https://github.com/facebook/react/pull/28942.patch",
        "merged_at": null
    },
    "body": "## Summary\r\n\r\nThis pull request simplifies the type definition of `pendingState` in the `useActionState` hook by changing it from `Thenable<boolean> | boolean` to just `boolean`.\r\nThe current implementation of `useActionState` defines the type of `pendingState` as `Thenable<boolean> | boolean.` However, upon closer inspection of the code, it appears that `pendingState` is always set to a boolean value, either directly or via the `setPendingState` function, which only accepts a boolean argument.\r\n```ts\r\npendingStateHook = mountStateImpl((false: Thenable<boolean> | boolean));\r\nconst setPendingState: boolean => void = (dispatchOptimisticSetState.bind(\r\n  null,\r\n  currentlyRenderingFiber,\r\n  false,\r\n  ((pendingStateHook.queue: any): UpdateQueue<\r\n    S | Awaited<S>,\r\n    S | Awaited<S>,\r\n  >),\r\n): any);\r\n```\r\nIn the `dispatchActionState` function, `setPendingState `is always called with a boolean value:\r\n```ts\r\nsetPendingState(true);\r\n```\r\nTherefore, defining `pendingState` as `Thenable<boolean> | boolean` seems unnecessary, as it's never actually set to a thenable value. This pull request proposes to simplify the type to `boolean`, which more accurately reflects how `pendingState` is used in practice.\r\nThis change improves code clarity and maintainability by removing the potentially confusing `Thenable` type when it's not needed. It also aligns the type definition with the actual usage of `pendingState` throughout the `useActionState` implementation.\r\n\r\n### Comparison with `useTransition`\r\n\r\nWhile the code for pendingState in useActionState appears to have been developed with reference to the useTransition hook, it's important to note that these are two different cases that require different handling.\r\n\r\n In useTransition, `isPending` can actually hold a thenable value, as evidenced by this code:\r\n```ts\r\nfunction updateTransition(): [\r\n  boolean,\r\n  (callback: () => void, options?: StartTransitionOptions) => void,\r\n] {\r\n  const [booleanOrThenable] = updateState(false);\r\n  const hook = updateWorkInProgressHook();\r\n  const start = hook.memoizedState;\r\n  const isPending =\r\n    typeof booleanOrThenable === 'boolean'\r\n      ? booleanOrThenable\r\n      : // This will suspend until the async action scope has finished.\r\n        useThenable(booleanOrThenable);\r\n  return [isPending, start];\r\n}\r\n```\r\nHere, `booleanOrThenable` is the result of `updateState(false)`, and its type is `Thenable<boolean> | boolean`. The value of `isPending` depends on the type of `booleanOrThenable`:\r\n\r\n- If `booleanOrThenable` is a boolean,`isPending` directly uses that value.\r\n- If `booleanOrThenable` is a thenable object, `isPending` is assigned the result of processing the thenable with `useThenable`.\r\n\r\nTherefore, in `useTransition`, the `Thenable<boolean> | boolean` type is appropriate for `isPending`, as it can hold a thenable value.\r\nIn contrast, `pendingState` in `useActionState` is always used as a boolean value, so we can simplify its type to `boolean`. \r\n\r\n## How did you test this change?\r\n\r\nTo verify that this change doesn't introduce any regressions, I ran the existing test suite with `yarn test`. All tests passed without any issues, indicating that the updated type definition does not break any existing functionality.",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28942/reactions",
        "total_count": 1,
        "+1": 1,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28942/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28941",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28941/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28941/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28941/events",
    "html_url": "https://github.com/facebook/react/issues/28941",
    "id": 2267306465,
    "node_id": "I_kwDOAJy2Ks6HJFnh",
    "number": 28941,
    "title": "Bug [React-DOM]: Missing \"bun\" export field in package.json",
    "user": {
        "login": "Guibi1",
        "id": 36936511,
        "node_id": "MDQ6VXNlcjM2OTM2NTEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/36936511?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Guibi1",
        "html_url": "https://github.com/Guibi1",
        "followers_url": "https://api.github.com/users/Guibi1/followers",
        "following_url": "https://api.github.com/users/Guibi1/following{/other_user}",
        "gists_url": "https://api.github.com/users/Guibi1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Guibi1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Guibi1/subscriptions",
        "organizations_url": "https://api.github.com/users/Guibi1/orgs",
        "repos_url": "https://api.github.com/users/Guibi1/repos",
        "events_url": "https://api.github.com/users/Guibi1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Guibi1/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 155984160,
            "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
            "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
            "name": "Status: Unconfirmed",
            "color": "d4c5f9",
            "default": false,
            "description": "A potential issue that we haven't yet confirmed as a bug"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-28T02:44:30Z",
    "updated_at": "2024-04-28T02:47:47Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "In the exports field of the `react-dom`'s package.json, there is no \"bun\" field. Bun defaults to the \"default\" field for compatibility. However, the `./server.node.js` file doesn't export `renderToReadableStream()`, while Bun supports Web Streams out of the box.\r\n\r\nSee: [The Bun doc on Module resolution](https://bun.sh/docs/runtime/modules#importing-packages)\r\nThis issue is similar to #26906, but Bun always supported Web Streams so there is no backwards compatibility issues.\r\n\r\nReact version: 18.3.1\r\n\r\n## Steps To Reproduce\r\n\r\n1. Install `react-dom`.\r\n2. Import `renderToReadableStream()`\r\n3. Run the file using Bun\r\n4. Notice that the error is something like this: `SyntaxError: Export named 'renderToReadableStream' not found in module '~/??/node_modules/react-dom/server.node.js'.`, which clearly shows that Bun uses the default export.\r\n\r\nLink to code example:\r\nI am not sure how to use Bun on the browser.\r\n\r\n## The current behavior\r\n\r\nBun uses the default export. (aka server.node.js)\r\n\r\n## The expected behavior\r\n\r\nBun uses a custom \"bun\" export. (aka server.browser.js)\r\n\r\nI have tested the following change locally and it completely fixes this issue:\r\n\r\n![fixed package.json](https://github.com/facebook/react/assets/36936511/08a9d496-edaf-48eb-9d41-e07c1b00a084)",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28941/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28941/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28940",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28940/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28940/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28940/events",
    "html_url": "https://github.com/facebook/react/pull/28940",
    "id": 2267162928,
    "node_id": "PR_kwDOAJy2Ks5t6kFt",
    "number": 28940,
    "title": "feat(hyperlink): added a hyperlink to Node in README.md file",
    "user": {
        "login": "itzzjb",
        "id": 95894819,
        "node_id": "U_kgDOBbc9Iw",
        "avatar_url": "https://avatars.githubusercontent.com/u/95894819?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/itzzjb",
        "html_url": "https://github.com/itzzjb",
        "followers_url": "https://api.github.com/users/itzzjb/followers",
        "following_url": "https://api.github.com/users/itzzjb/following{/other_user}",
        "gists_url": "https://api.github.com/users/itzzjb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/itzzjb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/itzzjb/subscriptions",
        "organizations_url": "https://api.github.com/users/itzzjb/orgs",
        "repos_url": "https://api.github.com/users/itzzjb/repos",
        "events_url": "https://api.github.com/users/itzzjb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/itzzjb/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2024-04-27T19:52:11Z",
    "updated_at": "2024-04-28T02:36:52Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28940",
        "html_url": "https://github.com/facebook/react/pull/28940",
        "diff_url": "https://github.com/facebook/react/pull/28940.diff",
        "patch_url": "https://github.com/facebook/react/pull/28940.patch",
        "merged_at": null
    },
    "body": "As a fellow beginner to React, I didn't even know React runs on top of Node when I started. \r\n\r\nSo, some beginners might get confused about what is Node and how to find details about it or how to download it. \r\n\r\nSo, I thought to add a hyperlink to Node replacing the word Node in the README.md file. I think this might be a valuable contribution. \r\n\r\n- Januda",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28940/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28940/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28939",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28939/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28939/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28939/events",
    "html_url": "https://github.com/facebook/react/pull/28939",
    "id": 2267161855,
    "node_id": "PR_kwDOAJy2Ks5t6j4T",
    "number": 28939,
    "title": "Import correct prod version of jsx-dev-runtime for react-server",
    "user": {
        "login": "eps1lon",
        "id": 12292047,
        "node_id": "MDQ6VXNlcjEyMjkyMDQ3",
        "avatar_url": "https://avatars.githubusercontent.com/u/12292047?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eps1lon",
        "html_url": "https://github.com/eps1lon",
        "followers_url": "https://api.github.com/users/eps1lon/followers",
        "following_url": "https://api.github.com/users/eps1lon/following{/other_user}",
        "gists_url": "https://api.github.com/users/eps1lon/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eps1lon/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eps1lon/subscriptions",
        "organizations_url": "https://api.github.com/users/eps1lon/orgs",
        "repos_url": "https://api.github.com/users/eps1lon/repos",
        "events_url": "https://api.github.com/users/eps1lon/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eps1lon/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        },
        {
            "id": 1775958285,
            "node_id": "MDU6TGFiZWwxNzc1OTU4Mjg1",
            "url": "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
            "name": "React Core Team",
            "color": "9149d1",
            "default": false,
            "description": "Opened by a member of the React Core Team"
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-27T19:48:46Z",
    "updated_at": "2024-04-27T20:25:28Z",
    "closed_at": "2024-04-27T20:25:26Z",
    "author_association": "COLLABORATOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28939",
        "html_url": "https://github.com/facebook/react/pull/28939",
        "diff_url": "https://github.com/facebook/react/pull/28939.diff",
        "patch_url": "https://github.com/facebook/react/pull/28939.patch",
        "merged_at": "2024-04-27T20:25:26Z"
    },
    "body": "Follow-up to https://github.com/facebook/react/pull/28921/",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28939/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28939/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28938",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28938/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28938/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28938/events",
    "html_url": "https://github.com/facebook/react/issues/28938",
    "id": 2267070212,
    "node_id": "I_kwDOAJy2Ks6HIL8E",
    "number": 28938,
    "title": "[React 19] Support scoped custom element registries (i.e, react with Custom Elements being rendered in a shadow root)",
    "user": {
        "login": "michaelwarren1106",
        "id": 8377369,
        "node_id": "MDQ6VXNlcjgzNzczNjk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8377369?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/michaelwarren1106",
        "html_url": "https://github.com/michaelwarren1106",
        "followers_url": "https://api.github.com/users/michaelwarren1106/followers",
        "following_url": "https://api.github.com/users/michaelwarren1106/following{/other_user}",
        "gists_url": "https://api.github.com/users/michaelwarren1106/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/michaelwarren1106/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/michaelwarren1106/subscriptions",
        "organizations_url": "https://api.github.com/users/michaelwarren1106/orgs",
        "repos_url": "https://api.github.com/users/michaelwarren1106/repos",
        "events_url": "https://api.github.com/users/michaelwarren1106/events{/privacy}",
        "received_events_url": "https://api.github.com/users/michaelwarren1106/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-27T15:49:45Z",
    "updated_at": "2024-04-27T16:02:35Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "## Summary\r\n\r\n**This is not an issue, but a (hopefully small) feature request/enhancement to the Custom Element support coming in React 19.**\r\n\r\nThe Custom Element support in React 19 is awesome! But even once React 19 lands, there will still be one challenge that Custom Element component library maintainers face. There is no way to inform React to use a scoped custom element registry when creating elements.\r\n\r\n### Scoped Custom Element Registries\r\n\r\n[Proppsal](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md)\r\n\r\nThe above proposal implements a new `CustomElementRegistry()` api where Custom Element authors can register custom elements to a registry that is not the global registry. An implementation of scoped custom element registries is in [Chrome Canary](https://chromestatus.com/feature/5090435261792256) under a flag at the moment, and the Web Components Community Group is working to see them implemented in all browsers.\r\n\r\nThere are also several polyfills that add this behavior to browsers in the meantime. Here is the one I use:\r\n\r\n[Polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry)\r\n\r\n### Use case: Micro-frontend application\r\n\r\nMicro-frontend application architectures are very common. This pattern is where a host application will use module federation (webpack, vite etc) to dynamically fetch JS modules containing separate \"remote applications\" that the host app then assembles into a single seamless application for the user. The architecture is popular because it enables autonomy of releases between remote applications.\r\n\r\nFor Custom Elements though, the problem is that with only the single global Custom Element registry in browsers, remotes can't scope their Custom Elements efectively and so there can be version conflicts when remote applications depend on different version of the same custom element. Whichever version gets registered first \"wins\" and the other remotes break.\r\n\r\nScoped element registries solve this. If a remote application is rendered inside a shadow root (custom element, or just a div with an attached shadow root) then all Custom Element definitions in that remote can be pulled from a scoped registry instead of the global one. Bye bye version conflicts! Every remote gets its own version of the Custom Elements it uses.\r\n\r\n\r\n### Feature Request\r\nIf the remote application uses a framework like React where `document.createElement` is used. In order to create a scoped Custom Element using the scoped definition in the custom registry, `shadowRoot.createElement()` is the mechanism.\r\n\r\nReact (and other frameworks also) have no way to be informed that they are being rendered inside a shadow root with a scoped registry attached. And therefore have no mechanism to switch from `document.createElement` to `shadowRoot.createElement`. React can already render inside a shadow root just fine. React's root can be an element inside a shadow root with no issues. This feature is about detecting whether or not React's render root has a parent element that is a shadow root and switching to `shadowRoot.createElement()` accordingly.\r\n\r\nI hope this is enough detail to describe the ask. I would think that this might not be a huge feature or change to existing React fundamentals, but I'm not an expert on what the exact implementation approach should be. I'm just familiar with the current problem landscape and our workarounds that we use to get around it being cumbersome.\r\n\r\n[This comment](https://github.com/WICG/webcomponents/issues/1043#issuecomment-1883480452) in a thread about the topic has a rough idea of what the implementation might look like.\r\n\r\nI would think that with an implementation similar to the above, `document.createElement()` would be used in applications where there aren't any scoped element registry polyfills, or where the feature hasn't yet landed natively in browsers, so there may be low risk to a check for \"is the root node in a shadow root\".\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28938/reactions",
        "total_count": 7,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 4,
        "rocket": 3,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28938/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28937",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28937/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28937/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28937/events",
    "html_url": "https://github.com/facebook/react/pull/28937",
    "id": 2267055459,
    "node_id": "PR_kwDOAJy2Ks5t6OL6",
    "number": 28937,
    "title": "Fixed it: Update CODE_OF_CONDUCT.md",
    "user": {
        "login": "bimsonz",
        "id": 6716652,
        "node_id": "MDQ6VXNlcjY3MTY2NTI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6716652?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bimsonz",
        "html_url": "https://github.com/bimsonz",
        "followers_url": "https://api.github.com/users/bimsonz/followers",
        "following_url": "https://api.github.com/users/bimsonz/following{/other_user}",
        "gists_url": "https://api.github.com/users/bimsonz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bimsonz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bimsonz/subscriptions",
        "organizations_url": "https://api.github.com/users/bimsonz/orgs",
        "repos_url": "https://api.github.com/users/bimsonz/repos",
        "events_url": "https://api.github.com/users/bimsonz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bimsonz/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2024-04-27T15:09:09Z",
    "updated_at": "2024-04-27T15:52:54Z",
    "closed_at": "2024-04-27T15:52:54Z",
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28937",
        "html_url": "https://github.com/facebook/react/pull/28937",
        "diff_url": "https://github.com/facebook/react/pull/28937.diff",
        "patch_url": "https://github.com/facebook/react/pull/28937.patch",
        "merged_at": null
    },
    "body": "Blame @ThePrimeagen\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28937/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28937/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28936",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28936/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28936/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28936/events",
    "html_url": "https://github.com/facebook/react/pull/28936",
    "id": 2267052318,
    "node_id": "PR_kwDOAJy2Ks5t6NlC",
    "number": 28936,
    "title": "feat(badge): Add JSDelivr badge",
    "user": {
        "login": "Zaid-maker",
        "id": 53424436,
        "node_id": "MDQ6VXNlcjUzNDI0NDM2",
        "avatar_url": "https://avatars.githubusercontent.com/u/53424436?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Zaid-maker",
        "html_url": "https://github.com/Zaid-maker",
        "followers_url": "https://api.github.com/users/Zaid-maker/followers",
        "following_url": "https://api.github.com/users/Zaid-maker/following{/other_user}",
        "gists_url": "https://api.github.com/users/Zaid-maker/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Zaid-maker/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Zaid-maker/subscriptions",
        "organizations_url": "https://api.github.com/users/Zaid-maker/orgs",
        "repos_url": "https://api.github.com/users/Zaid-maker/repos",
        "events_url": "https://api.github.com/users/Zaid-maker/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Zaid-maker/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-27T15:00:55Z",
    "updated_at": "2024-04-28T07:15:26Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28936",
        "html_url": "https://github.com/facebook/react/pull/28936",
        "diff_url": "https://github.com/facebook/react/pull/28936.diff",
        "patch_url": "https://github.com/facebook/react/pull/28936.patch",
        "merged_at": null
    },
    "body": "## Summary\r\n\r\nAdds a Jsdelivr badge which shows how much downloads React has in Month through [jsdelivr](https://www.jsdelivr.com/package/npm/react) CDN\r\n\r\n![image](https://github.com/facebook/react/assets/53424436/eab282e1-3f74-4428-afa7-b2e018fc1208)\r\n\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28936/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28936/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28935",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28935/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28935/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28935/events",
    "html_url": "https://github.com/facebook/react/issues/28935",
    "id": 2267023515,
    "node_id": "I_kwDOAJy2Ks6HIAib",
    "number": 28935,
    "title": "[React 19] Eslint React JSDoc support",
    "user": {
        "login": "eduardocque",
        "id": 35545218,
        "node_id": "MDQ6VXNlcjM1NTQ1MjE4",
        "avatar_url": "https://avatars.githubusercontent.com/u/35545218?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eduardocque",
        "html_url": "https://github.com/eduardocque",
        "followers_url": "https://api.github.com/users/eduardocque/followers",
        "following_url": "https://api.github.com/users/eduardocque/following{/other_user}",
        "gists_url": "https://api.github.com/users/eduardocque/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eduardocque/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eduardocque/subscriptions",
        "organizations_url": "https://api.github.com/users/eduardocque/orgs",
        "repos_url": "https://api.github.com/users/eduardocque/repos",
        "events_url": "https://api.github.com/users/eduardocque/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eduardocque/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-27T13:44:55Z",
    "updated_at": "2024-04-27T13:45:15Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "## Summary\r\n\r\n<!--\r\n  Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a\r\n  repository on GitHub, or provide a minimal code example that reproduces the\r\n  problem. You may provide a screenshot of the application if you think it is\r\n  relevant to your bug report. Here are some tips for providing a minimal\r\n  example: https://stackoverflow.com/help/mcve.\r\n-->\r\n\r\nbased on react 19 documentation `prop-types` is gone, so for JS users the only way to manage it is using JSDoc, can be possible to support jsdoc prop-type validation in eslint-plugin-react ?\r\n\r\nExample\r\n```js\r\n/**\r\n * @param {{\r\n *   content?: string,\r\n *   requiredParameter: string // required parameter if not can be with \"?\"\r\n * }} props\r\n * @returns {React.ReactElement}\r\n */\r\nconst ChildElement = props => {\r\n  const { content = '' } = props;\r\n\r\n  return <div>{content}</div>;\r\n};\r\n\r\n/** @returns {React.ReactElement} */\r\nconst ParentElement = () => {\r\n  return <ChildElement content=\"Hello World\" wrongParameter=\"test\" />;\r\n};\r\n```\r\n\r\nin this example\r\n* wrongParameter should be marked as error due that is not in ChildElement JSDocs\r\n* whole component should mark an error due that requiredParameter that exists in the JSDoc is not defined from the parent element\r\n\r\nthe intention of this request if to give some ways in javascrit to work without involve typescript to maange types and props",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28935/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28935/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28934",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28934/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28934/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28934/events",
    "html_url": "https://github.com/facebook/react/pull/28934",
    "id": 2266856463,
    "node_id": "PR_kwDOAJy2Ks5t5o0s",
    "number": 28934,
    "title": "fix(hydrateRoot): to check and add validations for type check of arguments in hydrateRoot while development",
    "user": {
        "login": "Shubhdeep12",
        "id": 43654389,
        "node_id": "MDQ6VXNlcjQzNjU0Mzg5",
        "avatar_url": "https://avatars.githubusercontent.com/u/43654389?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Shubhdeep12",
        "html_url": "https://github.com/Shubhdeep12",
        "followers_url": "https://api.github.com/users/Shubhdeep12/followers",
        "following_url": "https://api.github.com/users/Shubhdeep12/following{/other_user}",
        "gists_url": "https://api.github.com/users/Shubhdeep12/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Shubhdeep12/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Shubhdeep12/subscriptions",
        "organizations_url": "https://api.github.com/users/Shubhdeep12/orgs",
        "repos_url": "https://api.github.com/users/Shubhdeep12/repos",
        "events_url": "https://api.github.com/users/Shubhdeep12/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Shubhdeep12/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-27T05:54:33Z",
    "updated_at": "2024-04-27T05:59:41Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28934",
        "html_url": "https://github.com/facebook/react/pull/28934",
        "diff_url": "https://github.com/facebook/react/pull/28934.diff",
        "patch_url": "https://github.com/facebook/react/pull/28934.patch",
        "merged_at": null
    },
    "body": "\r\n<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `main`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test --prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn test --debug --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\nfixes: #28792 \r\nAdded a validation and type check for arguments of hydrateRoot\r\n<!--\r\n Explain the **motivation** for making this change. What existing problem does the pull request solve?\r\n-->\r\n\r\n## How did you test this change?\r\n\r\n<!--\r\n  Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface.\r\n  How exactly did you verify that your PR solves the issue you wanted to solve?\r\n  If you leave this empty, your PR will very likely be closed.\r\n-->\r\n\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28934/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28934/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28933",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28933/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28933/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28933/events",
    "html_url": "https://github.com/facebook/react/issues/28933",
    "id": 2266446889,
    "node_id": "I_kwDOAJy2Ks6HFzwp",
    "number": 28933,
    "title": "[React 19]",
    "user": {
        "login": "1372594487",
        "id": 66430889,
        "node_id": "MDQ6VXNlcjY2NDMwODg5",
        "avatar_url": "https://avatars.githubusercontent.com/u/66430889?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/1372594487",
        "html_url": "https://github.com/1372594487",
        "followers_url": "https://api.github.com/users/1372594487/followers",
        "following_url": "https://api.github.com/users/1372594487/following{/other_user}",
        "gists_url": "https://api.github.com/users/1372594487/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/1372594487/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/1372594487/subscriptions",
        "organizations_url": "https://api.github.com/users/1372594487/orgs",
        "repos_url": "https://api.github.com/users/1372594487/repos",
        "events_url": "https://api.github.com/users/1372594487/events{/privacy}",
        "received_events_url": "https://api.github.com/users/1372594487/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-26T20:18:05Z",
    "updated_at": "2024-04-26T20:31:05Z",
    "closed_at": "2024-04-26T20:31:05Z",
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "## Summary\r\n\r\n<!--\r\n  Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a\r\n  repository on GitHub, or provide a minimal code example that reproduces the\r\n  problem. You may provide a screenshot of the application if you think it is\r\n  relevant to your bug report. Here are some tips for providing a minimal\r\n  example: https://stackoverflow.com/help/mcve.\r\n-->\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28933/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28933/timeline",
    "performed_via_github_app": null,
    "state_reason": "not_planned",
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28932",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28932/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28932/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28932/events",
    "html_url": "https://github.com/facebook/react/pull/28932",
    "id": 2266417763,
    "node_id": "PR_kwDOAJy2Ks5t4IFs",
    "number": 28932,
    "title": "Add changelog for 18.3.1",
    "user": {
        "login": "rickhanlonii",
        "id": 2440089,
        "node_id": "MDQ6VXNlcjI0NDAwODk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2440089?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rickhanlonii",
        "html_url": "https://github.com/rickhanlonii",
        "followers_url": "https://api.github.com/users/rickhanlonii/followers",
        "following_url": "https://api.github.com/users/rickhanlonii/following{/other_user}",
        "gists_url": "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rickhanlonii/subscriptions",
        "organizations_url": "https://api.github.com/users/rickhanlonii/orgs",
        "repos_url": "https://api.github.com/users/rickhanlonii/repos",
        "events_url": "https://api.github.com/users/rickhanlonii/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rickhanlonii/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        },
        {
            "id": 1775958285,
            "node_id": "MDU6TGFiZWwxNzc1OTU4Mjg1",
            "url": "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
            "name": "React Core Team",
            "color": "9149d1",
            "default": false,
            "description": "Opened by a member of the React Core Team"
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-26T19:52:45Z",
    "updated_at": "2024-04-26T20:03:57Z",
    "closed_at": "2024-04-26T20:03:03Z",
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28932",
        "html_url": "https://github.com/facebook/react/pull/28932",
        "diff_url": "https://github.com/facebook/react/pull/28932.diff",
        "patch_url": "https://github.com/facebook/react/pull/28932.patch",
        "merged_at": "2024-04-26T20:03:03Z"
    },
    "body": null,
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28932/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28932/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28931",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28931/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28931/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28931/events",
    "html_url": "https://github.com/facebook/react/issues/28931",
    "id": 2266304064,
    "node_id": "I_kwDOAJy2Ks6HFQ5A",
    "number": 28931,
    "title": "E-Commerce",
    "user": {
        "login": "donnadonwhite",
        "id": 128304336,
        "node_id": "U_kgDOB6XE0A",
        "avatar_url": "https://avatars.githubusercontent.com/u/128304336?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/donnadonwhite",
        "html_url": "https://github.com/donnadonwhite",
        "followers_url": "https://api.github.com/users/donnadonwhite/followers",
        "following_url": "https://api.github.com/users/donnadonwhite/following{/other_user}",
        "gists_url": "https://api.github.com/users/donnadonwhite/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/donnadonwhite/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/donnadonwhite/subscriptions",
        "organizations_url": "https://api.github.com/users/donnadonwhite/orgs",
        "repos_url": "https://api.github.com/users/donnadonwhite/repos",
        "events_url": "https://api.github.com/users/donnadonwhite/events{/privacy}",
        "received_events_url": "https://api.github.com/users/donnadonwhite/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-26T18:29:47Z",
    "updated_at": "2024-04-26T19:26:53Z",
    "closed_at": "2024-04-26T19:26:53Z",
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "1) Unique features of e-commerce are ubiquity, customization, interactivity, and global reaching [how plagiarism checker work](https://plagiarismsearch.com/how-plagiarism-checker-work.html).  Other features include social technology, personalization, universal standards, information density, and richness. All these aspects have contributed to the modern marketing and selling approaches that help identify and influence target audiences with the purpose of selling them products and services.\r\n2) The first problem is easy access to content and infrastructure. The second one is the lack of regulation in security, privacy, and consumer rights protection. Intellectual property rights and international trade regulation are important issues due to the global nature of e-commerce.\r\n3) An elevator pitch is a presentation that lasts for not more than three minutes, during which an entrepreneur has to convince investors to invest their money in one’s business. The key elements are an introduction, the background of the idea, market opportunity, revenue metrics, funding, and exit strategy.\r\n4) Business model disruption has four stages. The first one implies that the disruption creates new products, usually of low quality and price, but disruptors also look for new financial resources for business. During the second stage, the products, that have been created during the first one, are improved to become valuable and attract customers from the incumbents’ market. The business process of selling a new product becomes important during the third stage. The ending, or the fourth stage, comes when incumbents lose a market share or move to another market. Thus, finding new customers is another option for incumbents to survive.\r\n5) Web page data is located on the host’s Web server, but in order to be delivered to the Internet, it has to move through the host company’s network. The next process is data distribution from the ISP’s network to smaller ones. Then, the ISP that serves my network, receives data. Finally, the access point allows the Web page data to be downloaded directly and wirelessly to my tablet.\r\n6) The World Wide Web was born in 1989 thanks to Berners-Lee. He was the creator of HTML language and he gave the Internet to civilians. Andreessen created a Mosaic web browser with simple graphics and a user interface. The first commercial browser appeared in 1994, a year after the era of the commercial civilian Internet had begun.\r\n7) The Internet and the Web have offered easy and convenient access to the product, information, and feedback about it. In other words, they created the concept of online shopping. The numerous features of the Internet support e-commerce. These are text, voice, and video communication tools, search engines, streaming media, and social networks. The first three features have improved communication between customers and businesses, while search engine provides information and feedback that help customers decide what to buy. Finally, streaming and social media is a convenient platform for advertising and marketing.\r\n8) The process of developing an e-commerce presence for a typical start-up Web site over a one-year period implies such phases, activities, and milestones. The first phase is planning, and it includes such important activities as foreseeing e-commerce presence and staff employment, while the milestone is a mission statement. The second phase is the website development stage, filled with such activities as designing a website, gathering content, and finding a hosting; the milestone here is a website plan. The third phase is called web implementation, so its activities presuppose the development of keywords, search engine optimization, and searching for possible sponsors, while a well-developed functioning website is a milestone. The next phase is creating a media plan, but to design it, the project needs such activities as the recognition of appropriate social media platforms and the production of content that suits them; consequently, a milestone here is a social media plan. Social media implementation is the fifth phase, during which the project has to develop its presence on the most popular social networks. Therefore, a milestone for this phase implies a properly working social media presence. The activities of a mobile plan, which is the sixth phase, include developing this plan and examining a website for smartphones. Consequently, a mobile media plan is a milestone for this phase.\r\n9) E-commerce merchant server software provides online catalogs, shopping carts, and online credit cards. Their aim is to make online shopping easy and enjoyable. The functionalities are the adherence to business and technological standards, multicultural capability, the ability to connect to the existing business model, and an advanced reporting system.\r\n10) An e-commerce business will be successful if its design has eight factors. Informational factor helps users find more information about products. The navigation and work with the website must be easy. Additional navigation also is a vital factor for e-commerce success so that customers can scroll a website according to their preference in techniques. The process of making a purchase must be easy, and the site should be available from different browsers. The seventh factor is graphics since the customer should have the option to control the sounds and visual animation if they disrupt one’s buying experience. Finally, legible text helps in achieving success for e-commerce business since customers must be able to read clearly from the site.\r\n11) The Internet of Things (IoT) is the technology that connects any device that has sensors to the Internet. The IoT is applicable to any devices nowadays, from cars or houses to clothes, watches, and so on. The first security issue of the IoT is its interoperability. Others are security and privacy since the devices are personalized but vulnerable to patches.\r\n12) Secure Sockets Layer/Transport Layer Security is the protocol for data encryption, and server and client authentication that allows users to identify a server and securely connect to it. A secure negotiated session is a client-server session that contains encrypted information such as content, the content of forms, the URL of needed documents, and cookies. During this session, the system uses the session key. A session key is a one-time-used encryption that allows a new device to apply for a secure session. VPN enables remote users to access internal networks securely via the Internet, using authentication and encryption.\r\n13) The term Big Data describes data sets that have been received from various sources. Its amount is so big that no technology can store and analyze it in time. Marketers want to receive relevant feedback from the audience about their purchasing behavior or products. This data would help in fixing the business process immediately and improve issues in marketing products and services.\r\n14) The Internet made companies and customers closer since they directly interact online, which allows them to discuss their preferences, feedback, and needs. Therefore, the first three main impacts of the Internet on marketing are personalization, participative marketing, and improved peer-to-peer communication between companies and buyers. The fourth impact is a communal one.\r\n15) CRM is a storage of all interactions between a client and a firm. Its functions are being familiar with a customer profile, storing information about contacts, and making contacts and a profile available for all employees of the firm.\r\n16) Location-based mobile marketing uses personal navigation, reviews of visited places, finder of friends in the crowd, and tracker services to find children or points of interest.\r\n17) Marketers like local mobile marketing since companies can interact with the domestic target market. The local population is interested in purchasing products from local companies. Therefore, market players want to use this opportunity.\r\n18) The five-step process includes an accurate description of facts, a determination of the conflict and involved values, and the definition of stakeholders. The last two processes are finding the options to take and identifying possible consequences. The best principle is to imagine oneself in someone else’s place since this helps evaluate the fairness of a decision. Applying the collective utilitarian principle is another option, and the action in this situation is taken to benefit more people.\r\n19) The purpose of intellectual property law is to provide a balance between the public interest of the distribution of intellectual property and the private interest of creators to save a monopoly for tangible and intangible products, generated in the human mind. Types of intellectual property protection are trademark law, patent, and copyright.\r\n20) Online retailers face difficulties since the pioneers of this industry dealt with a small number of users and the shipping price for large-sized items was high. They also charged low prices for their products and services, but they did not work on a business strategy. After 2015, when customers started to prefer online shopping to offline and fees decreased, the earnings started to grow constantly and surpass the profits of offline market competitors. Online retailers understood that consumers valued convenience more than rice.\r\n21) Online career services are so well suited to the Web as they have reduced total hiring time and provided efficient services for an employer and a candidate. Thus, online career services can pre-screen a person before an interview, which will allow them to avoid a meeting with unqualified candidates since such situations often arise in internal referral programs.\r\n22) The three basic revenue models for digital content delivery are subscription, a la carte subscription, and advertising-supported. In the subscription model, a customer receives all content from the resource they have chosen. A la carte subscription is a form of subscription, but the user pays for the content they use. Advertising-supported revenue model provides content for free, but the company receives revenue from advertising. Such a model means that the quality of content is low, but it is still entertaining.\r\n23) Pure digital news sites do not spend money for printing their content on paper, and they can easily convert to more efficient business processes. Such sites offer user-generated content and employ innovation to generate news quickly. Traditional print newspapers have quality journalism, they are reliable, and they spread accurate information.\r\n24) Social networks are used as a marketing tool, advertisement, and branding resource. Communication between a customer and companies has become direct since every user can post feedback about the product and a firm can see it and respond. Businesses care about their online reputation as they check comments from consumers all the time. Therefore, they are afraid of public pressure in case of a failure to meet customers’ needs or to improve products and services.\r\n25) Online auctions have four major types. The English auction implies that a seller sells a single item, the process has a time limit, and multiple buyers participate in bidding. The Dutch auction helps sell numerous identical items. During the Name Your Own Price auction, buyers tell the price and sellers bid. Usually, such auctions sell vacation packages, airline tickets, or hotel reservations. Finally, penny auction is an event, where participants pay for bidding on the site beforehand, and the fee varies from 50 cents to a dollar. The main difference between this and other auction types that even if a participant does not purchase anything, they still pay for participation and bidding.\r\n\r\n\r\n",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28931/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28931/timeline",
    "performed_via_github_app": null,
    "state_reason": "not_planned",
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28930",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28930/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28930/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28930/events",
    "html_url": "https://github.com/facebook/react/pull/28930",
    "id": 2266267409,
    "node_id": "PR_kwDOAJy2Ks5t3m-0",
    "number": 28930,
    "title": "Configure JSX Feature Flags as Dynamic (React Native @ Meta)",
    "user": {
        "login": "yungsters",
        "id": 55161,
        "node_id": "MDQ6VXNlcjU1MTYx",
        "avatar_url": "https://avatars.githubusercontent.com/u/55161?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/yungsters",
        "html_url": "https://github.com/yungsters",
        "followers_url": "https://api.github.com/users/yungsters/followers",
        "following_url": "https://api.github.com/users/yungsters/following{/other_user}",
        "gists_url": "https://api.github.com/users/yungsters/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/yungsters/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yungsters/subscriptions",
        "organizations_url": "https://api.github.com/users/yungsters/orgs",
        "repos_url": "https://api.github.com/users/yungsters/repos",
        "events_url": "https://api.github.com/users/yungsters/events{/privacy}",
        "received_events_url": "https://api.github.com/users/yungsters/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-04-26T18:03:41Z",
    "updated_at": "2024-04-26T18:28:46Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28930",
        "html_url": "https://github.com/facebook/react/pull/28930",
        "diff_url": "https://github.com/facebook/react/pull/28930.diff",
        "patch_url": "https://github.com/facebook/react/pull/28930.patch",
        "merged_at": null
    },
    "body": "## Summary\r\n\r\nWe are almost ready to experiment with enabling `enableRefAsProp` and `disableStringRefs` in React Native at Meta. My plan is to enable and validate both at the same time, in order to minimize the time that we introduce these dynamic checks in the hot code path of JSX.\r\n\r\n## How did you test this change?\r\n\r\n```\r\n$ yarn test\r\n$ yarn flow fabric\r\n```",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28930/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28930/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28929",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28929/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28929/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28929/events",
    "html_url": "https://github.com/facebook/react/pull/28929",
    "id": 2266135604,
    "node_id": "PR_kwDOAJy2Ks5t3Jpr",
    "number": 28929,
    "title": "Add changelog for 18.3",
    "user": {
        "login": "rickhanlonii",
        "id": 2440089,
        "node_id": "MDQ6VXNlcjI0NDAwODk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2440089?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rickhanlonii",
        "html_url": "https://github.com/rickhanlonii",
        "followers_url": "https://api.github.com/users/rickhanlonii/followers",
        "following_url": "https://api.github.com/users/rickhanlonii/following{/other_user}",
        "gists_url": "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rickhanlonii/subscriptions",
        "organizations_url": "https://api.github.com/users/rickhanlonii/orgs",
        "repos_url": "https://api.github.com/users/rickhanlonii/repos",
        "events_url": "https://api.github.com/users/rickhanlonii/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rickhanlonii/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        },
        {
            "id": 1775958285,
            "node_id": "MDU6TGFiZWwxNzc1OTU4Mjg1",
            "url": "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
            "name": "React Core Team",
            "color": "9149d1",
            "default": false,
            "description": "Opened by a member of the React Core Team"
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2024-04-26T16:36:39Z",
    "updated_at": "2024-04-26T20:06:39Z",
    "closed_at": "2024-04-26T16:45:08Z",
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28929",
        "html_url": "https://github.com/facebook/react/pull/28929",
        "diff_url": "https://github.com/facebook/react/pull/28929.diff",
        "patch_url": "https://github.com/facebook/react/pull/28929.patch",
        "merged_at": "2024-04-26T16:45:08Z"
    },
    "body": "Fixes https://github.com/facebook/react/issues/28924",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28929/reactions",
        "total_count": 4,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 4,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28929/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "done"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28928",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28928/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28928/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28928/events",
    "html_url": "https://github.com/facebook/react/issues/28928",
    "id": 2266127634,
    "node_id": "I_kwDOAJy2Ks6HEl0S",
    "number": 28928,
    "title": "[React 19] react-test-renderer deprecation",
    "user": {
        "login": "iammerrick",
        "id": 109635,
        "node_id": "MDQ6VXNlcjEwOTYzNQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/109635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/iammerrick",
        "html_url": "https://github.com/iammerrick",
        "followers_url": "https://api.github.com/users/iammerrick/followers",
        "following_url": "https://api.github.com/users/iammerrick/following{/other_user}",
        "gists_url": "https://api.github.com/users/iammerrick/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/iammerrick/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/iammerrick/subscriptions",
        "organizations_url": "https://api.github.com/users/iammerrick/orgs",
        "repos_url": "https://api.github.com/users/iammerrick/repos",
        "events_url": "https://api.github.com/users/iammerrick/events{/privacy}",
        "received_events_url": "https://api.github.com/users/iammerrick/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 6688277426,
            "node_id": "LA_kwDOAJy2Ks8AAAABjqcDsg",
            "url": "https://api.github.com/repos/facebook/react/labels/React%2019",
            "name": "React 19",
            "color": "263258",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2024-04-26T16:31:00Z",
    "updated_at": "2024-04-27T12:23:09Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "## Summary\r\n\r\nToday our team relies on react-test-renderer to render a JSON tree which is subsequently used for search indexing. By rendering to JSON we have a structure we can use to extract semantic data like `title`, `meta`, `description`, etc. To do something similar without `react-test-renderer` we'd have to render to HTML, and then use an HTML parser to parse and extract semantic data.\r\n\r\nI realize that this is an \"off label\" use of React Test Renderer but I was hoping there would be an alternative to with `react-test-renderer`'s deprecation.\r\n\r\n```tsx\r\nReactTestRenderer.create(reactElement).toJSON();\r\n```",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28928/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28928/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "todo"
},
{
    "url": "https://api.github.com/repos/facebook/react/issues/28927",
    "repository_url": "https://api.github.com/repos/facebook/react",
    "labels_url": "https://api.github.com/repos/facebook/react/issues/28927/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react/issues/28927/comments",
    "events_url": "https://api.github.com/repos/facebook/react/issues/28927/events",
    "html_url": "https://github.com/facebook/react/pull/28927",
    "id": 2266045728,
    "node_id": "PR_kwDOAJy2Ks5t2180",
    "number": 28927,
    "title": "[Not for merge] 18.3.1 Release",
    "user": {
        "login": "acdlite",
        "id": 3624098,
        "node_id": "MDQ6VXNlcjM2MjQwOTg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3624098?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/acdlite",
        "html_url": "https://github.com/acdlite",
        "followers_url": "https://api.github.com/users/acdlite/followers",
        "following_url": "https://api.github.com/users/acdlite/following{/other_user}",
        "gists_url": "https://api.github.com/users/acdlite/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/acdlite/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/acdlite/subscriptions",
        "organizations_url": "https://api.github.com/users/acdlite/orgs",
        "repos_url": "https://api.github.com/users/acdlite/repos",
        "events_url": "https://api.github.com/users/acdlite/events{/privacy}",
        "received_events_url": "https://api.github.com/users/acdlite/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 196858374,
            "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
            "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
            "name": "CLA Signed",
            "color": "e7e7e7",
            "default": false,
            "description": null
        },
        {
            "id": 1775958285,
            "node_id": "MDU6TGFiZWwxNzc1OTU4Mjg1",
            "url": "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
            "name": "React Core Team",
            "color": "9149d1",
            "default": false,
            "description": "Opened by a member of the React Core Team"
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2024-04-26T15:40:00Z",
    "updated_at": "2024-04-26T16:52:55Z",
    "closed_at": "2024-04-26T16:52:54Z",
    "author_association": "COLLABORATOR",
    "active_lock_reason": null,
    "draft": true,
    "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/28927",
        "html_url": "https://github.com/facebook/react/pull/28927",
        "diff_url": "https://github.com/facebook/react/pull/28927.diff",
        "patch_url": "https://github.com/facebook/react/pull/28927.patch",
        "merged_at": null
    },
    "body": "Includes:\r\n\r\n- https://github.com/facebook/react/pull/28916",
    "reactions": {
        "url": "https://api.github.com/repos/facebook/react/issues/28927/reactions",
        "total_count": 1,
        "+1": 1,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/facebook/react/issues/28927/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "status": "done"
}]